

export const BASEMENT_LENGTH = 3;
export const BASEMENT_WIDTH = 2;
export const STEPS_IN_SINGLE_TRACK = 24;
export const STEPS_IN_WHOLE_TRACK_COUNT = 256;
export const STEPS_IN_UNIT = STEPS_IN_WHOLE_TRACK_COUNT / BASEMENT_LENGTH;
export const TRACK_DISTANCE = 0.75;
